# Generated by Django 5.0.6 on 2024-05-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_email_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='defult'),
            preserve_default=False,
        ),
    ]
