# Generated by Django 5.0.6 on 2024-05-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallapp', '0002_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(),
        ),
    ]
